version: '2'

services:
  app:
    build: .
    ports:
      - 5000:5000
    volumes:
      - ./data/:/src/data
    environment:
      - input_file_path=/src/data/RFID-Study-Task-Generation/output/MASTER/tasks-MASTER-training.json
      - output_file_path=/src/data/output.log
